### ISSUE TITLE
Can't install/run test

### ISSUE THREAD

**Issue by nadiadavidson** [Oshlack/MINTIE#1]
Can't install or run test.
Using miniconda3 (Miniconda3-latest-Linux-x86_64.sh from 16/1/20)
python 3.7.4

Issues:
#1 samtools wouldn't install with the automatic script
#2 pysam python module wouldn't compile for this version of python/conda.

**Comment by nadiadavidson** [comment]
More detail:
gcc is version 4.9.4
pybedtools also failed to install

**Comment by mcmero** [comment]
Thanks for raising the issues. Samtools can be tricky to install as it must be compiled from source. The zlib and curses libraries dependencies will have to be installed prior to installing Samtools. Please see the [Samtools install documentation](https://github.com/samtools/samtools/blob/develop/INSTALL). 

In a cluster environment, I would recommend loading samtools as a module. In `bpipe.config` set:

```
modules="samtools"
```
(check with your cluster admins for the exact package name/version.)
And in your `tools.groovy` set:
```
samtools="samtools"
``` 

Similarly with python dependencies, these will have to be troubleshooted on an individual basis if the automatic installation fails. This may be due to missing dependencies. Pysam for instance requires a C compiler and all [dependencies of htslib](https://github.com/samtools/htslib/blob/1.10.2/INSTALL). Please see the [pysam documentation](https://pysam.readthedocs.io/en/latest/installation.html) for further details. 

I have added a [Troubleshooting](https://github.com/Oshlack/MINTIE/wiki/Install#troubleshooting) section on the wiki to point users in the right direction for installation issues.
